"""Application constants."""

# Window
WINDOW_TITLE = "PDF Editor"
WINDOW_SIZE = "1200x800"
APPEARANCE_MODE = "dark"
COLOR_THEME = "blue"

# Zoom
ZOOM_DEFAULT = 1.0
ZOOM_MIN = 0.25
ZOOM_MAX = 4.0
ZOOM_STEP = 0.1

# Thumbnail sidebar
THUMBNAIL_WIDTH = 150
THUMBNAIL_SIDEBAR_WIDTH = 180

# Properties panel
PROPERTIES_PANEL_WIDTH = 200

# Rendering
RENDER_DPI = 150

# Annotation defaults
DEFAULT_ANNOT_COLOR = "#FF0000"
DEFAULT_HIGHLIGHT_COLOR = "#FFFF00"
DEFAULT_TEXT_COLOR = "#000000"
DEFAULT_OPACITY = 0.5
DEFAULT_FONT_SIZE = 12
DEFAULT_BORDER_WIDTH = 2

# Colors
CANVAS_BG = "#404040"
ACTIVE_THUMBNAIL_BORDER = "#3B8ED0"
THUMBNAIL_BORDER = "#555555"

# Lazy thumbnail threshold
LAZY_THUMBNAIL_THRESHOLD = 100

# --- Continuous viewport ---
PAGE_GAP = 12
PAGE_SHADOW_OFFSET = 4
PAGE_SHADOW_COLOR = "#2a2a2a"
OVERSCAN_PX = 200
PAGE_CACHE_SIZE = 20

# --- Sidebar ---
SIDEBAR_WIDTH = 220

# --- Tab bar ---
TAB_HEIGHT = 32
TAB_MAX_TITLE_LEN = 25

# --- Recent files ---
RECENT_FILES_MAX = 10

# --- Search ---
SEARCH_HIGHLIGHT_COLOR = "#FFD700"
SEARCH_ACTIVE_COLOR = "#FF6600"
