"""Application constants and configuration."""
from app.version import APP_NAME

# Window
WINDOW_TITLE = APP_NAME
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
MIN_WIDTH = 800
MIN_HEIGHT = 600

# Zoom
ZOOM_DEFAULT = 1.0
ZOOM_MIN = 0.25
ZOOM_MAX = 4.0
ZOOM_STEP = 0.1

# Thumbnail sidebar
THUMBNAIL_WIDTH = 150
THUMBNAIL_SIDEBAR_WIDTH = 180

# Properties panel
PROPERTIES_PANEL_WIDTH = 200

# Rendering
RENDER_DPI = 150

# Annotation defaults
DEFAULT_ANNOT_COLOR = "#FF0000"
DEFAULT_HIGHLIGHT_COLOR = "#FFFF00"
DEFAULT_TEXT_COLOR = "#000000"
DEFAULT_OPACITY = 0.5
DEFAULT_FONT_SIZE = 12
DEFAULT_BORDER_WIDTH = 2

# Continuous viewport
PAGE_GAP = 12
PAGE_SHADOW_OFFSET = 4
OVERSCAN_PX = 200
PAGE_CACHE_SIZE = 20

# Sidebar
SIDEBAR_WIDTH = 220

# Tab bar
TAB_HEIGHT = 32
TAB_MAX_TITLE_LEN = 25

# Recent files
RECENT_FILES_MAX = 10

# Search
SEARCH_HIGHLIGHT_COLOR = "#FFD700"
SEARCH_ACTIVE_COLOR = "#FF6600"

# Markdown editor
MD_FONT_FAMILY = "Consolas"
MD_FONT_SIZE = 13
MD_LINE_NUMBER_BG = "#2d2d2d"
MD_LINE_NUMBER_FG = "#858585"
MD_PREVIEW_CSS_BG = "#1e1e1e"
MD_PREVIEW_CSS_FG = "#cccccc"

# Obsidian
DEFAULT_VAULT_PATH = ""

# Sticky notes
STICKY_NOTE_DIR = ".docview/sticky-notes"
STICKY_NOTE_WIDTH = 250
STICKY_NOTE_HEIGHT = 250
STICKY_AUTOSAVE_MS = 500

# Supported file extensions
PDF_EXTENSIONS = {".pdf"}
MARKDOWN_EXTENSIONS = {".md", ".markdown", ".mdown", ".mkd"}
ALL_SUPPORTED_EXTENSIONS = PDF_EXTENSIONS | MARKDOWN_EXTENSIONS
